model:
  base_model: "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"
  max_length: 512
  learning_rate: 1e-5
  batch_size: 8
  num_epochs: 10
  warmup_steps: 2000
  weight_decay: 0.005
  save_steps: 500
  logging_steps: 50
  output_dir: "./models/checkpoints"
  
lora:
  r: 8
  lora_alpha: 16
  lora_dropout: 0.05
  target_modules: ["q_proj", "v_proj"]
  bias: "none"
  task_type: "CAUSAL_LM"

training:
  gradient_accumulation_steps: 4
  fp16: false
  gradient_checkpointing: true
  evaluation_strategy: "steps"
  eval_steps: 500
  save_total_limit: 3
  load_best_model_at_end: true
  metric_for_best_model: "loss"
  greater_is_better: false
  remove_unused_columns: false

data:
  train_file: "./data/processed/stock_train.json"
  validation_file: "./data/processed/stock_validation.json"
  preprocessing_num_workers: 4
  max_train_samples: null  # 设置为null表示使用全部数据
  max_eval_samples: null

logging:
  log_level: "info"
  log_to_file: true
  log_file: "./logs/training.log"
  tensorboard_log_dir: "./logs/tensorboard"
  report_to: ["tensorboard"]
