model:
  base_model: "deepseek-r1-1.5b"
  max_length: 512
  learning_rate: 3e-5
  batch_size: 16
  num_epochs: 5
  warmup_steps: 1000
  weight_decay: 0.01
  save_steps: 1000
  logging_steps: 100
  output_dir: "./models/checkpoints"

training:
  gradient_accumulation_steps: 4
  fp16: true
  gradient_checkpointing: true
  evaluation_strategy: "steps"
  eval_steps: 500
  save_total_limit: 3
  load_best_model_at_end: true
  metric_for_best_model: "loss"
  greater_is_better: false

data:
  train_file: "./data/processed/train.json"
  validation_file: "./data/processed/validation.json"
  preprocessing_num_workers: 4
  max_train_samples: null  # 设置为null表示使用全部数据
  max_eval_samples: null

logging:
  log_level: "info"
  log_to_file: true
  log_file: "./logs/training.log"
  tensorboard_log_dir: "./logs/tensorboard"
  report_to: ["tensorboard"] 